/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BaseBreadCrumb: typeof import('./components/BaseBreadCrumb/index.vue')['default']
    BaseCodeView: typeof import('./components/BaseCodeView/index.vue')['default']
    BaseDot: typeof import('./components/BaseDot/index.tsx')['default']
    BaseForm: typeof import('./components/BaseForm/src/BaseForm.vue')['default']
    BaseIcon: typeof import('./components/BaseIcon/index.vue')['default']
    BaseIconSelector: typeof import('./components/BaseIconSelector/index.vue')['default']
    BaseOption: typeof import('./components/BaseOption/index.vue')['default']
    BaseOptionItem: typeof import('./components/BaseOptionItem/index.vue')['default']
    BaseOverflowTags: typeof import('./components/BaseOverflowTags/index.vue')['default']
    BaseTable: typeof import('./components/BaseTable/index.vue')['default']
    BaseTag: typeof import('./components/BaseTag/index.tsx')['default']
    BaseThemeButton: typeof import('./components/BaseThemeButton/index.vue')['default']
    ParentView: typeof import('./components/ParentView/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Src: typeof import('./components/BaseForm/src/index.vue')['default']
  }
}
